const Protocol = {
  S_PLAYER_NAME: "S_PLAYER_NAME",
  S_MATCHES_LIST: "S_MATCHES_LIST",
  S_PLAYERS_LIST: "S_PLAYERS_LIST",
  
  S_INIT_MATCH: "S_INIT_MATCH",
  S_START_MATCH: "S_START_MATCH",
  S_LEAVE_MATCH: "S_LEAVE_MATCH",
  
  S_GAME_OVER: "S_GAME_OVER",
  S_GOAL: "S_GOAL",
  S_MATCH_DATA: "S_MATCH_DATA",
  S_HOST_PLAYER_CHANGED: "S_HOST_PLAYER_CHANGED",
  
  S_OPPONENT_CONNECTED: "S_OPPONENT_CONNECTED",
  S_OPPONENT_POS: "S_OPPONENT_POS",
  S_OPPONENT_LEAVED: "S_OPPONENT_LEAVED",
  S_OPPONENT_DISCONNECTED: "S_OPPONENT_DISCONNECTED",
///
  S_INIT_AS_A: "S_INIT_AS_A",
  S_INIT_AS_B: "S_INIT_AS_B",

//-----------------------------------

  C_LOGIN: "C_LOGIN",
  C_RENAME: "C_RENAME",
  C_PLAYER_NAME: "C_PLAYER_NAME",
  C_CREATE_MATCH: "C_CREATE_MATCH",
  C_JOIN_MATCH: "C_JOIN_MATCH",
  C_LEAVE_MATCH: "C_LEAVE_MATCH",
  C_MATCH_DATA: "C_MATCH_DATA",
  C_PLAYER_POS: "C_PLAYER_POS",
  C_GOAL: "C_GOAL",
  C_SWITCH_HOST_PLAYER: "C_SWITCH_HOST_PLAYER",

  CONNECT: "connect",
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
};

module.exports = Protocol;